### ISSUE TITLE
Does not propagate changes to the repository input

### ISSUE THREAD

**Issue by antifuchs** [benesch/pulumi-docker-buildkit#1]
I just saw an issue where the `imageDigest` didn't change after an image was uploaded to a recreated repository (this is `pulumi destroy` & `pulumi up`). The pulumi stack contained no references to the old ECR registry *except* in the image's `imageDigest` output. Weirdly enough, the `name` contained the right URL.

**Comment by benesch** [comment]
Fixed for real in v0.1.3. I was able to repro this with the sample program in https://github.com/benesch/pulumi-docker-buildkit/tree/master/examples/aws-python, and verified that v0.1.3 always correctly chooses the RepoDigest from the correct repo.
